### ISSUE TITLE
Missing TypeScript definition in the latest version 1.0.5

### ISSUE THREAD

**Issue by apfritts** [courtneypattison/react-native-fade-in-out#22]
For some reason my TS isn't picking up the TypeScript definitions any more. I can see that this project is written in TS but @courtneypattison do you know if there might be other configuration I need to setup? I've reverted to 1.0.4 which seems to work correctly.

**Comment by courtneypattison** [comment]
@apfritts Thank you so much for letting me know! I think I fixed the issue in v 1.0.6. If you could let me know, I would really appreciate it. It seems like the definitions have to be in the root directory of the package. For some reason, I thought the "types" key in the package.json specified the location of the definitions file.

**Comment by apfritts** [comment]
Sweet! Thanks!!
